Add lock and unlock enpoints to WDA
appium/WebDriverAgent pull request #8
Opened 2017-12-04 22:02 UTC by umutuzgur

2017-12-05 12:59 UTC, imurchie reviewed
This _seems_ ok to me.

2017-12-05 13:10 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +static bool locked = FALSE;
`FALSE` - > `NO`

2017-12-05 13:11 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +    if(state == 0) {
`locked = state != 0`

2017-12-05 13:11 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +static bool locked = FALSE;
I'd prefer `isLocked` or `isScreenLocked` more

2017-12-05 13:12 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +    return TRUE;
-> YES

2017-12-05 13:13 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +  SEL mSelector = NSSelectorFromString(@"pressLockButton");
You can add this method into private headers. There is no need to use NSInvokation. See https://github.com/facebook/WebDriverAgent/commit/e3134dbc3c5093de8ec244d92e1a79282667f2e8 for the reference

2017-12-05 13:14 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +  [self fb_goToHomescreenWithError:NULL];
cannot we just call `pressHomeButton` native method two times instead?

2017-12-05 13:15 UTC, mykola-mokhnach commented on WebDriverAgentLib/Commands/FBCustomCommands.m
> +    [[FBRoute PUT:@"/lock"].withoutSession respondWithTarget:self action:@selector(handleLock:)],
do we need PUT endpoints? I'd rather create to POST for changing the state and one for getting the current state

2017-12-05 13:16 UTC, mykola-mokhnach commented
An integration test would be nice

2017-12-05 13:17 UTC, mykola-mokhnach requested changes
please add at least one integration test

2017-12-05 13:25 UTC, mykola-mokhnach commented on WebDriverAgentLib/Commands/FBCustomCommands.m
> +    [[FBRoute PUT:@"/lock"].withoutSession respondWithTarget:self action:@selector(handleLock:)],
laso for Appium it makes sense to duplicate these endpoints, so they can be also used together with session id

2017-12-05 13:46 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +- (BOOL)fb_unlockScreen:(NSError **)error
this will, most likely, fail for iOS < 10, since it requires single swipe in order to unlock the screen

2017-12-08 15:55 UTC, mykola-mokhnach commented on WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m
> +  SEL mSelector = NSSelectorFromString(@"pressLockButton");
`performSelector` might be shorter. It is anyway not needed to pass any arguments there

2017-12-14 10:46 UTC, mykola-mokhnach commented
@umutuzgur would you mind to finish the PR?

2017-12-14 10:47 UTC, umutuzgur commented
@mykola-mokhnach I will focus on it next week. I'm quite busy at the moment

2018-01-02 15:08 UTC, closed without merging